#!/bin/sh

WORKSPACES=10

workspaces() {
  # Lees alle workspaces uit inclusief de titels van alle vensters en groepeer dit per workspace.
  WORKSPACE_CLIENTS=$(hyprctl clients -j | jq 'group_by(.workspace.id) | map ({key: (.[0].workspace.id | tostring), value: [.[] | .title]}) | from_entries')
  seq 1 $WORKSPACES | jq --argjson windows "${WORKSPACE_CLIENTS}" --slurp -Mc 'map(tostring) | map({id: . | tonumber, windows: ($windows[.]//[]) | join("\n")})'
}

activewindow() {
  WINDOW_TITLE=$(hyprctl activewindow -j | jq --raw-output .title)
  OUTPUT=""

  declare -A apps=(
    ["󰈹 Firefox"]="(.*)Mozilla Firefox$"
    [" vim"]="vim"
    ["󰙯 Discord"]="(.*) - Discord"
  )

  for key in "${!apps[@]}"; do
    if [[ `echo $WINDOW_TITLE | grep -E "${apps[$key]}"` ]]; then
      OUTPUT="$key"
      break 
    fi
  done

  if [[ "$OUTPUT" == "" ]]; then 
    echo "`echo $WINDOW_TITLE | cut -c 1-10`..."
  else
    echo $OUTPUT
  fi
}

if [[ $1 == 'workspaces' ]] ; then
  # Beginstand
  echo "{\"workspaces\": $(workspaces), \"active\": 1}"
  
  # Lees continu de staat van de werkbladen uit de Hyprland-socket.
  socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    # Wordt er van werkblad gewisseld?
    if [[ ${line:0:9} == "workspace" ]]; then
      # Bepaal het geactiveerde werkblad.
      active=${line:11:2}

      if [[ "$active" != "" ]]; then
        # Werk de waarde in EWW bij.
        eww update workspaces="{\"workspaces\": $(workspaces), \"active\": $active}"
      fi
    fi
  done
fi

if [[ $1 == 'activewindow' ]]; then 
  # Druk actieve venster af.
  activewindow
  # Lees uit de Hyprland-socket wat het venster is als er gewisseld wordt.
  socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    activewindow
  done
fi
