[global/wm]
margin-bottom = 0
margin-top = 0

[color]
background = #25252d
background-transparent = #cc25252d
foreground = #ffffff
comment = #5c6bc0
selected = #5657f5
available = #9e9ff9
inactive = #4b9e9ff9
red = #ef5350 
pink = #ef4f9c
orange = #ff6d00 
purple = #7c4dff
green = #00c853 
yellow = #ffee00

include-file = ~/.config/polybar/hardware.ini
include-file = ~/.config/polybar/media.ini
include-file = ~/.config/polybar/system.ini

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = false
format = <label-state>
format-font = 5
label-monitor = %name%
label-active = " %name% "
label-active-foreground = ${color.foreground}
label-active-background = ${color.selected}
label-occupied = " %name% "
label-occupied-foreground = ${color.available}
label-urgent = " %name% "
label-urgent-foreground = ${color.background}
label-urgent-background = ${color.red}
label-empty = " %name% "
label-empty-foreground = ${color.inactive}
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1

[module/spc]
type = custom/text
content = " "

[module/weather]
type = custom/script
exec = python3 ~/.config/polybar/scripts/weather.py
interval = 600
format-foreground = ${color.orange}
cursor-click = python3 ~/.config/polybar/scripts/weather.py
label-font = 2

;
; APPS
;
[module/firefox]
type = custom/text
content = " "
content-foreground = #fe5733
content-font = 6
click-left = firefox &

[module/thunderbird]
type = custom/text
content = " "
content-foreground = #0066cc
content-font = 6
click-left = thunderbird-beta &

[module/telegram]
type = custom/text
content = " "
content-foreground = #1c9fda
content-font = 6
click-left = telegram-desktop &

[module/discord]
type = custom/text
content = "ﭮ "
content-foreground = #7289da
content-font = 6
click-left = discord &

[module/keepass]
type = custom/text
content = " "
content-foreground = #519738
content-font = 6
click-left = keepassxc &

[module/chatterino]
type = custom/text
content = " "
content-foreground = #88cefe
content-font = 6
click-left = chatterino &

;
; BARS
;

[bar/base]
override-redirect = true
fixed-center = true
locale = nl_NL.UTF-8

width = 100%
height = 34
offset-x = 0%
offset-y = 0%
padding = 0
module-margin-left = 0
module-margin-right = 0

background = ${color.background-transparent}
foreground = ${color.foreground}

border-size = 0.0
radius = 0.0
radius-top = 0.0
radius-bottom = 0.0
line-size = 2
line-color = ${color.background}
border-bottom-size = 0
border-bottom-color = ${color.foreground}

font-0 = "Roboto Mono Nerd Font:size=10;3"
font-1 = "Roboto Condensed:size=10;3"
font-2 = "M+ 2c:size=10;3"
font-3 = "Roboto Condensed:style=Bold:size=10;3"
font-4 = "Roboto Mono Nerd Font:style=Bold:size=10;3"
font-5 = "Roboto Mono Nerd Font:size=12;3"

separator = 
dim-value = 1.0
wm-name =
wm-restack = bspwm
enable-ipc = true
cursor-click = pointer

[bar/main]
inherit = bar/base

monitor = DP-0
monitor-strict = true

modules-left = workspaces 
modules-center = mpd
modules-right = updates spc weather spc pulseaudio-control spc date spc spc session-menu

tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background-transparent}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 1
tray-scale = 1.0

[bar/secondary]
inherit = bar/base

monitor = DP-4
monitor-strict = true

modules-left = workspaces
modules-right = cpu spc temp-cpu spc temp-gpu spc kernel spc

[bar/single-head]
inherit = bar/base

modules-left = workspaces spc spc firefox spc thunderbird spc keepass spc telegram spc discord spc chatterino
modules-center = mpd
modules-right = updates spc spc wifi spc weather spc backlight spc battery spc pulseaudio-control spc spc date spc spc session-menu

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = false

; https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
