;
; MODULES VOOR HARDWARE-INFORMATIE
;
[module/cpu]
type = internal/cpu
interval = 1
format = <label>
format-prefix = 
format-prefix-foreground = ${color.comment}
label = " %percentage%%"
label-font = 2

[module/memory]
type = internal/memory
interval = 1
format = <label>
format-prefix = 
format-prefix-foreground = ${color.comment}
label = " %gb_used%"
label-font = 2

[module/fs]
type = internal/fs
mount-0 = /
interval = 30
fixed-values = true
format-mounted = <label-mounted>
format-mounted-prefix = 
format-mounted-prefix-foreground = ${color.comment}
label-mounted = " %free%"
label-mounted-font = 2
label-unmounted = "%mountpoint%: offline"
label-unmounted-font = 2

[module/temp]
type = internal/temperature
interval = 2
thermal-zone = 0
base-temperature = 40
warn-temperature = 75
units = true
label = %temperature-c%
label-font = 2
label-warn = "%temperature-c%"
label-warn-foreground = ${color.red}
label-warn-font = 2
format-font = 2
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-foreground = ${color.comment}

[module/temp-cpu]
inherit = module/temp
hwmon-path = ${env:X_CPU_HWMON}
format = <ramp> cpu <label>
format-warn = <ramp> cpu <label-warn>

[module/temp-cpu-sm]
inherit = module/temp
hwmon-path = ${env:X_CPU_HWMON}
format = <ramp> <label>
format-warn = <ramp> <label-warn>

[module/temp-gpu]
inherit = module/temp
hwmon-path = ${env:X_GPU_HWMON}
format = <ramp> gpu <label>
format-warn = <ramp> gpu <label-warn>

[module/backlight]
type = internal/backlight
; ls -l /sys/class/backlight
card = amdgpu_bl0
format = <ramp> <label>
label = %percentage%%
label-font = 2
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 
ramp-6 = 
ramp-foreground = ${color.purple}

[module/battery]
type = internal/battery
full-at = 98
; ls -l /sys/class/power_supply
battery = BAT1
adapter = ACAD
poll-interval = 5
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <label-full>
format-full-prefix = 
format-full-prefix-foreground = ${color.pink}
label-charging = %percentage%%
label-charging-font = 2
label-discharging = %percentage%%
label-discharging-font = 2
label-full = 100%
label-full-font = 2
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
ramp-capacity-foreground = ${color.purple}
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 
animation-charging-framerate = 750
animation-charging-foreground = ${color.orange}

[module/wifi]
type = internal/network
interface = wlan0
interval = 1
format-connected = <label-connected>
format-connected-prefix = "直 "
format-connected-prefix-foreground = ${color.purple}
format-disconnected = <label-disconnected>
format-disconnected-prefix = "睊 "
format-disconnected-prefix-foreground = ${color.red}
label-connected = " %essid%"
label-connected-font = 2
label-disconnected = "geen verbinding"
label-disconnected-font = 2