;
; MODULES VOOR MULTIMEDIAGERELATEERDE INSTELLINGEN EN APPLICATIES
;

[module/mpd]
type = internal/mpd
interval = 1
format-online = <label-song> <label-time>
;format-online-prefix = ﱘ
format-online-prefix = 蓼
format-online-prefix-foreground = ${color.available}
format-offline = <label-offline>
format-offline-prefix =
format-offline-prefix-foreground = ${color.red}
label-song = " %artist% - %title%"
label-song-maxlen = 80
label-song-ellipsis = true
label-song-font = 4
label-time = %elapsed% / %total%
label-time-foreground = ${color.available}
label-time-padding = 1
label-time-font = 4
label-offline = " offline"
label-offline-font = 4

[module/mpd-mini]
type = internal/mpd
interval = 1
format-online = <label-song> <label-time>
format-online-prefix = "蓼 "
format-online-prefix-foreground = ${color.comment}
format-offline = <label-offline>
format-offline-prefix = "蓼 "
format-offline-prefix-foreground = ${color.red}
label-song = "%title%/%artist%"
label-song-maxlen = 25
label-song-ellipsis = true
label-song-font = 4
label-time = %elapsed%
label-time-foreground = ${color.comment}
label-time-padding = 0
label-time-font = 4
label-offline = " offline"
label-offline-font = 4

; Module voor het tonen en beheren van het volume.
; https://github.com/marioortizmanero/polybar-pulseaudio-control
[module/pulseaudio-control]
type = custom/script
tail = true
label-foreground = ${color.foreground}
label-font = 2
exec = pulseaudio-control --icons-volume "%{F#9e9ff9}%{F-} ,%{F#9e9ff9}%{F-} " --icon-muted " " --format "\$VOL_ICON \${VOL_LEVEL}%" listen
click-right = exec pavucontrol-qt &
click-left = ~/.config/sxhkd/scripts/change-volume.sh mute
scroll-up = ~/.config/sxhkd/scripts/change-volume.sh +2%
scroll-down = ~/.config/sxhkd/scripts/change-volume.sh -2%