;
; MODULES VOOR SYSTEEMGERELATEERDE ZAKEN
;
[module/date]
type = internal/date
interval = 1
date = %a %e %b,
date-alt = week %U van %Y
time = %H:%M
format = <label>
label = %date% %time%
label-font = 4

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
format-prefix = " "
format-prefix-foreground = ${color.comment}
label-layout = " %layout%"
label-indicator-on = "%name%"
label-indicator-on-foreground = ${color.red}
label-font = 2

; Module voor uitloggen, herstarten, slapen en uitschakelen van de computer.
[module/session-menu]
type = custom/menu
expand-right = false
label-open = " "
label-open-foreground = ${color.available}
label-close = " "
label-close-foreground = ${color.available}
menu-0-0 = " "
menu-0-0-exec = bspc quit
menu-0-0-foreground = ${color.pink}
menu-0-1 = " "
menu-0-1-exec = systemctl suspend
menu-0-1-foreground = ${color.comment}
menu-0-2 = " "
menu-0-2-exec = systemctl reboot
menu-0-2-foreground = ${color.orange}
menu-0-3 = " "
menu-0-3-exec = systemctl poweroff
menu-0-3-foreground = ${color.red}

; Kernelinformatie
[module/kernel]
type = custom/script
exec = uname -r | sed --regexp-extend "s/\-arch.+//g" 
tail = false
interval = 1024
format-foreground = ${color.foreground}
format-background = ${color.background}
format-prefix = " "
format-prefix-foreground = ${color.comment}
label-font = 2

; Package updates
[module/updates]
type = custom/script
exec = ~/.config/polybar/scripts/check-all-updates.sh
interval = 600
label = %output%
label-font = 2
format-foreground = ${color.foreground}
format-background = ${color.background-transparent}
format-prefix = " "
;format-prefix = "漣 "
format-prefix-foreground = ${color.available}
